/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "arrays.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Ideal_Pressure, Ideal_Pressure, AUTO)


PB_BIND(Pragmatic_VDW_Pressure, Pragmatic_VDW_Pressure, AUTO)



