/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_ARRAYS_PB_H_INCLUDED
#define PB_ARRAYS_PB_H_INCLUDED
#include <nanopb_example/pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Ideal_Pressure {
    pb_size_t volume_count;
    float volume[4];
    pb_size_t num_moles_count;
    float num_moles[4];
    pb_size_t r_constant_count;
    float r_constant[4];
    pb_size_t temperature_count;
    float temperature[4];
} Ideal_Pressure;

typedef struct _Pragmatic_VDW_Pressure {
    pb_size_t a_constant_count;
    float a_constant[4];
    pb_size_t num_moles_count;
    float num_moles[4];
    pb_size_t volume_count;
    float volume[4];
    pb_size_t b_constant_count;
    float b_constant[4];
    pb_size_t r_constant_count;
    float r_constant[4];
    pb_size_t temperature_count;
    float temperature[4];
} Pragmatic_VDW_Pressure;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Ideal_Pressure_init_default              {0, {0, 0, 0, 0}, 0, {0, 0, 0, 0}, 0, {0, 0, 0, 0}, 0, {0, 0, 0, 0}}
#define Pragmatic_VDW_Pressure_init_default      {0, {0, 0, 0, 0}, 0, {0, 0, 0, 0}, 0, {0, 0, 0, 0}, 0, {0, 0, 0, 0}, 0, {0, 0, 0, 0}, 0, {0, 0, 0, 0}}
#define Ideal_Pressure_init_zero                 {0, {0, 0, 0, 0}, 0, {0, 0, 0, 0}, 0, {0, 0, 0, 0}, 0, {0, 0, 0, 0}}
#define Pragmatic_VDW_Pressure_init_zero         {0, {0, 0, 0, 0}, 0, {0, 0, 0, 0}, 0, {0, 0, 0, 0}, 0, {0, 0, 0, 0}, 0, {0, 0, 0, 0}, 0, {0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define Ideal_Pressure_volume_tag                1
#define Ideal_Pressure_num_moles_tag             2
#define Ideal_Pressure_r_constant_tag            3
#define Ideal_Pressure_temperature_tag           4
#define Pragmatic_VDW_Pressure_a_constant_tag    5
#define Pragmatic_VDW_Pressure_num_moles_tag     6
#define Pragmatic_VDW_Pressure_volume_tag        7
#define Pragmatic_VDW_Pressure_b_constant_tag    8
#define Pragmatic_VDW_Pressure_r_constant_tag    9
#define Pragmatic_VDW_Pressure_temperature_tag   10

/* Struct field encoding specification for nanopb */
#define Ideal_Pressure_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, FLOAT,    volume,            1) \
X(a, STATIC,   REPEATED, FLOAT,    num_moles,         2) \
X(a, STATIC,   REPEATED, FLOAT,    r_constant,        3) \
X(a, STATIC,   REPEATED, FLOAT,    temperature,       4)
#define Ideal_Pressure_CALLBACK NULL
#define Ideal_Pressure_DEFAULT NULL

#define Pragmatic_VDW_Pressure_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, FLOAT,    a_constant,        5) \
X(a, STATIC,   REPEATED, FLOAT,    num_moles,         6) \
X(a, STATIC,   REPEATED, FLOAT,    volume,            7) \
X(a, STATIC,   REPEATED, FLOAT,    b_constant,        8) \
X(a, STATIC,   REPEATED, FLOAT,    r_constant,        9) \
X(a, STATIC,   REPEATED, FLOAT,    temperature,      10)
#define Pragmatic_VDW_Pressure_CALLBACK NULL
#define Pragmatic_VDW_Pressure_DEFAULT NULL

extern const pb_msgdesc_t Ideal_Pressure_msg;
extern const pb_msgdesc_t Pragmatic_VDW_Pressure_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Ideal_Pressure_fields &Ideal_Pressure_msg
#define Pragmatic_VDW_Pressure_fields &Pragmatic_VDW_Pressure_msg

/* Maximum encoded size of messages (where known) */
#define ARRAYS_PB_H_MAX_SIZE                     Pragmatic_VDW_Pressure_size
#define Ideal_Pressure_size                      80
#define Pragmatic_VDW_Pressure_size              120

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
