/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_PRES_PB_H_INCLUDED
#define PB_PRES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _PressureMeasurements {
    bool has_pressure;
    float pressure;
} PressureMeasurements;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define PressureMeasurements_init_default        {false, 0}
#define PressureMeasurements_init_zero           {false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define PressureMeasurements_pressure_tag        1

/* Struct field encoding specification for nanopb */
#define PressureMeasurements_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    pressure,          1)
#define PressureMeasurements_CALLBACK NULL
#define PressureMeasurements_DEFAULT NULL

extern const pb_msgdesc_t PressureMeasurements_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PressureMeasurements_fields &PressureMeasurements_msg

/* Maximum encoded size of messages (where known) */
#define PRES_PB_H_MAX_SIZE                       PressureMeasurements_size
#define PressureMeasurements_size                5

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
